name: CI-CD

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  unit-test:
    name: Unit Test
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_system: [ubuntu-latest, windows-latest]
        exclude:
          - nodejs_version: 18
            operating_system: windows-latest
    runs-on: ${{ matrix.operating_system }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v6
        with: 
          nodejs_version: ${{ matrix.nodejs_version }}

      - name: Install Dependencies
        run: npm install

      - name: Unit Test
        run: npm test

      - name: Upload Test Result
        uses: actions/upload-artifact@v7
        with:
          name: Test Result
          path: junit-report.xml
  
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS Version
        uses: actions/setup-node@v6

      - name: Install Dependencies
        run: npm install

      - name: Test Coverage
        run: npm run coverage

      - name: Upload Test Result
        uses: actions/upload-artifact@v7
        with:
          name: Test CoverageResult
          path: coverage